"""empty message

Revision ID: dbbfe255e7d3
Revises: 
Create Date: 2022-05-02 00:16:53.530379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbbfe255e7d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('delay', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('type_of_professor', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('attendancy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendancy_id'], ['attendancy.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('groups_id', sa.Integer(), nullable=False),
    sa.Column('proffesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groups_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['proffesor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('groups_id', 'proffesor_id')
    )
    op.create_table('projects',
    sa.Column('groups_id', sa.Integer(), nullable=False),
    sa.Column('projects_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['groups_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['projects_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('groups_id', 'projects_id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('Group_id', sa.Integer(), nullable=True),
    sa.Column('attendancy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['attendancy_id'], ['attendancy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('projects')
    op.drop_table('groups')
    op.drop_table('group')
    op.drop_table('project')
    op.drop_table('professor')
    op.drop_table('course')
    op.drop_table('attendancy')
    # ### end Alembic commands ###
